defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

general:
  n_freq_print: 5
  n_freq_checkpoint: 25
  start_save_epoch: 200
  ckpt_dir_name: 'ckpts'
  batch_size: 8
  n_epochs: 500