inputs:
  model_name: 'hyperpose'
  mode: 'test'
  backbone_path: './models/backbones/efficient-net-b0.pth'
  dataset_path: '/home/dev/Data/cambridge'
  labels_file: './datasets/CambridgeLandmarks/abs_cambridge_pose_sorted.csv_ShopFacade_test.csv'
  checkpoint_path: null
  models_path: '/media/dev/storage1/hyperpose_output/run_27_02_23_16_21'
  models_to_evaluate: null

general:
  n_freq_print: 5
  n_workers: 4
  devices_id: [0, 1, 2]
  save_hyper_weights_to_file: False

hyperpose:
  num_encoder_layers: 6
  dim_feedforward: 256
  hidden_dim: 256
  hyper_dim_t: 256
  hyper_dim_rot: 512
  use_quat_mul: False
  nheads: 4
  reduction:
    t: 'reduction_4'
    q: 'reduction_3'
  use_prior_t_for_rot: False